### PR TITLE
update regex to meet usecase of lifecycle badge embedded in a anchor tag

### LINKED ISSUE #135: Project Lifecycle Badge False Positives
**Describe the issue**
Multiple repos have been receiving multiple issues to create lifecycle badges even though they already exist.

**Additional context**
These repos use badge styling and reference-style links.

**Definition of done**
Stop creating issues for repos that already have lifecycle badges.  Limit those to one per repo.

Duplicated issues:
https://github.com/bcgov/containerization-and-cloud-economic-model/issues/21
https://github.com/bcgov/containerization-and-cloud-economic-model/issues/20
https://github.com/bcgov/containerization-and-cloud-economic-model/issues/19
https://github.com/bcgov/containerization-and-cloud-economic-model/issues/17
https://github.com/bcgov/site-status-checker/issues/11
https://github.com/bcgov/site-status-checker/issues/10
https://github.com/bcgov/site-status-checker/issues/9
https://github.com/bcgov/site-status-checker/issues/8
https://github.com/bcgov/site-status-checker/issues/6
https://github.com/bcgov/wps/issues/984
https://github.com/bcgov/wps/issues/970
https://github.com/bcgov/wps/issues/969
https://github.com/bcgov/wps/issues/961
https://github.com/bcgov/wps/issues/636

UPDATE - PR created: https://github.com/bcgov/repomountie/pull/137

### PR DESCRIPTION
**Pull request by patricksimonian**
#137 brought up an important usecase of the regex over validating a lifecycle badge. I've updated the regex and added a test case to work in this use case.

Fixes #135

### CODE REVIEW

**Review by DerekRoberts — APPROVED** [review]
Looks good!  I'll report back if any other false positives creep back in.

**Review by jleach — APPROVED** [review]

**Comment by DerekRoberts** [comment]
@jleach @patricksimonian More false positives, but only on one of three repos.  It looks like reference-style links aren't supported.

https://github.com/bcgov/containerizatiMore false positives, but only on one of three so far.  It looks like reference-style links aren't supported.

https://github.com/bcgov/containerization-and-cloud-economic-model/issues/22

Reference-style link:
```
[![Lifecycle][lifecycle-shield]](https://github.com/bcgov/repomountie/blob/master/doc/lifecycle-badges.md)
[lifecycle-shield]: https://img.shields.io/badge/Lifecycle-Stable-97ca00?style=for-the-badge
```on-and-cloud-economic-model/issues/22

Reference-style link:
```
[![Lifecycle][lifecycle-shield]](https://github.com/bcgov/repomountie/blob/master/doc/lifecycle-badges.md)
[lifecycle-shield]: https://img.shields.io/badge/Lifecycle-Stable-97ca00?style=for-the-badge
```

**Comment by jleach** [comment]
Haven used 'em before. This is where you put a URL elsewhere in your MD file and reference it (by name) elsewhere in the MD file. Ya? @DerekRoberts

**Comment by DerekRoberts** [comment]
> Haven used 'em before. This is where you put a URL elsewhere in your MD file and reference it (by name) elsewhere in the MD file. Ya? @DerekRoberts

@jleach That's right.  It wouldn't kill me to stop using reference-style links.  They're not useful enough I'd really miss them.

**Comment by DerekRoberts** [comment]
:+1:

**Pull request merged**
